FROM node:18.6-alpine as builder
WORKDIR /usr/prattle/client
COPY ./client/package.json .
RUN npm install --legacy-peer-deps
COPY ./client .
ARG REACT_APP_GOOGLE_SITE_KEY
ENV REACT_APP_GOOGLE_SITE_KEY $REACT_APP_GOOGLE_SITE_KEY
RUN npm run build

FROM nginx
COPY --from=builder /usr/prattle/client/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80